[package]
name = "untitled3"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3.26"
colored = "2.0"
jsonrpc-http-server = "15.0"
serde = { version = "1.0.203", features = ["derive"] }
sha2 = "0.11.0-pre.3"
serde_json = "1.0.118"
rand = "0.9.0-alpha.1"
hex = "0.4"